name: app_muchik
description: "app planifiko"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter_typeahead: ^5.2.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  image_picker: ^1.1.0  # Add this line
  cached_network_image: ^3.3.1
  fl_chart: ^0.65.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  month_year_picker: ^0.5.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.0
  file_saver: ^0.3.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_file_dialog: 3.0.2
  provider: ^6.1.5+1
  app_links: ^6.4.1
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3


flutter:

  uses-material-design: true
  assets:
    - assets/icon/logo4.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo4.jpg"


flutter_native_splash:
  # 1. AQUÍ pones tu color turquesa exacto
  color: "#FBFBFB"

  # 2. Tu imagen actual
  image: "assets/icon/logo4.jpg"

  # 3. Importante para Android 12+ (para que no salga un círculo blanco alrededor)
  android_12:
    image: "assets/icon/logo4.jpg"
    color: "#FBFBFB" # El mismo turquesa aquí
    icon_background_color: "#FBFBFB" # Y aquí también por si acaso

  # 4. Esto quita la barra de estado superior para dar más inmersión
  fullscreen: true